version: "3"
services:
  app: 
    build: .
    ports: 
      - "5000:80"
    depends_on:
      - redis
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: redis
    ports:
      - "6379:6379"

